using System;
using System.Collections.Generic;

namespace CCAdmin.Models
{
    public partial class StudentDetail
    {
        public int StudentDetailId { get; set; }
        public int StudentId { get; set; }
        public string AcademicYearId { get; set; }
        public string RefNo { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string SurnameAtBirth { get; set; }
        public string FirstForename { get; set; }
        public string OtherForenames { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string Sex { get; set; }
        public string Tel2 { get; set; }
        public string AltTel2 { get; set; }
        public string MobileTel { get; set; }
        public string Email { get; set; }
        public string Ni { get; set; }
        public string EthnicGroupId { get; set; }
        public bool? EuroResidentId { get; set; }
        public string CountryId { get; set; }
        public int? LocalDestinationId { get; set; }
        public string Childcare { get; set; }
        public string Identification { get; set; }
        public string WideningParticipationId { get; set; }
        public decimal? WideningParticipationFactor { get; set; }
        public bool QualOnEntryComplete { get; set; }
        public string AccommodationTypeId { get; set; }
        public int? BankId { get; set; }
        public int? BankBranchId { get; set; }
        public string AccountNoEncrypted { get; set; }
        public string NameOnAccountEncrypted { get; set; }
        public bool? SendMarketingInfo { get; set; }
        public int? SchoolId { get; set; }
        public string Ilaref { get; set; }
        public string IlarefConfirmedBy { get; set; }
        public DateTime? IlarefConfirmedDate { get; set; }
        public string AsylumSeekerRef { get; set; }
        public bool StudyElsewhere { get; set; }
        public string EmploymentBeneficiaries { get; set; }
        public string StudentInitiativeId { get; set; }
        public string FundingEntitlementId { get; set; }
        public string NationalityId { get; set; }
        public string HighestQualId { get; set; }
        public string SococcupationId { get; set; }
        public string LastInstitutionId { get; set; }
        public short? YearLeftLastInstitution { get; set; }
        public string NoOfAlevelsId { get; set; }
        public short? AlevelScore { get; set; }
        public string NoOfScehighersId { get; set; }
        public short? ScehighersScore { get; set; }
        public string NoOfVocationalQualsId { get; set; }
        public string Notes { get; set; }
        public DateTime? VlelastSent { get; set; }
        public DateTime? MostRecentProgrammeStartDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public int? Esfid { get; set; }
        public DateTime? EsfstartDate { get; set; }
        public DateTime? EsfendDate { get; set; }
        public string Upin { get; set; }
        public string LearnerSupportReason1Id { get; set; }
        public string LearnerSupportReason2Id { get; set; }
        public string LearnerSupportReason3Id { get; set; }
        public string LearnerSupportReason4Id { get; set; }
        public string PriorAttainmentLevelId { get; set; }
        public string StudentInitiative2Id { get; set; }
        public string LocalLearnerMonitoring1 { get; set; }
        public string LocalLearnerMonitoring2 { get; set; }
        public string ProviderSpecified1 { get; set; }
        public string ProviderSpecified2 { get; set; }
        public string PreviousRefNo { get; set; }
        public string FundingEntitlement2Id { get; set; }
        public bool Deleted { get; set; }
        public int? StaffId { get; set; }
        public bool LearningAgreementRequired { get; set; }
        public string SocioEconomicClassId { get; set; }
        public string PreviousStudentRefNo { get; set; }
        public string SupportRef { get; set; }
        public int? TutorId { get; set; }
        public int? DefaultExtraTime { get; set; }
        public bool DefaultSeparateRoom { get; set; }
        public string UserDefined1 { get; set; }
        public string UserDefined2 { get; set; }
        public string UserDefined3 { get; set; }
        public string UserDefined4 { get; set; }
        public string UserDefined5 { get; set; }
        public string UserDefined6 { get; set; }
        public string UserDefined7 { get; set; }
        public string UserDefined8 { get; set; }
        public string UserDefined9 { get; set; }
        public decimal? AdditionalSupportCost { get; set; }
        public string CreatedUsing { get; set; }
        public byte? InstitutionChoiceNumber { get; set; }
        public bool Hepreference { get; set; }
        public bool Exclude { get; set; }
        public DateTime? ExcludeFromDate { get; set; }
        public DateTime? ExcludeToDate { get; set; }
        public bool Overseas { get; set; }
        public int? PotentialStudentStatusId { get; set; }
        public string IndustrialSectorId { get; set; }
        public string ReferencesConfirmedBy { get; set; }
        public DateTime? ReferencesConfirmedDate { get; set; }
        public DateTime? LastOrganisationLeavingDate { get; set; }
        public byte IsPotentialStudent { get; set; }
        public int? HeardAboutCollegeId { get; set; }
        public string CarReg { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public bool EmastudentHasSignedPart2 { get; set; }
        public int? EmastudyPatternId { get; set; }
        public string EmacourseTypeId { get; set; }
        public int? EmafileSubmissionId { get; set; }
        public int? ReasonDidntEnrolId { get; set; }
        public int? EmasiteId { get; set; }
        public string EmaerrorText { get; set; }
        public bool Emaconfirmed { get; set; }
        public int? CollegeChoice { get; set; }
        public int? ContactPreference { get; set; }
        public bool StillAtLastSchool { get; set; }
        public bool IsAimHigher { get; set; }
        public bool? IsWheelchairUser { get; set; }
        public string Lscnumber { get; set; }
        public bool? Alsrequired { get; set; }
        public bool Algconfirmed { get; set; }
        public string ReferencesNotes { get; set; }
        public bool? HasPep { get; set; }
        public bool? MedicalDeclarationReceived { get; set; }
        public bool? MedicalConditionIdentified { get; set; }
        public string LearnerSupportType1Id { get; set; }
        public string LearnerSupportType2Id { get; set; }
        public string LearnerSupportType3Id { get; set; }
        public string LearnerSupportType4Id { get; set; }
        public short? UcastariffPoints { get; set; }
        public string UcasapplicationCode { get; set; }
        public int? HespecialFeeIndicatorId { get; set; }
        public string KnownAs { get; set; }
        public string UserDefined10 { get; set; }
        public string UserDefined11 { get; set; }
        public string UserDefined12 { get; set; }
        public string UserDefined13 { get; set; }
        public string UserDefined14 { get; set; }
        public string UserDefined15 { get; set; }
        public int? SupportNeed1Id { get; set; }
        public int? SupportNeed2Id { get; set; }
        public int? SupportNeed3Id { get; set; }
        public string DisabilityNotes { get; set; }
        public string PlaceOfBirth { get; set; }
        public DateTime? DateOfAddressCapture { get; set; }
        public string VerificationTypeId { get; set; }
        public string VerificationOtherDescription { get; set; }
        public byte? AbilityToShareId { get; set; }
        public string PostcodeOutEnrolment { get; set; }
        public string PostcodeInEnrolment { get; set; }
        public string ReasonForExclusion { get; set; }
        public bool EmadataSentSuccessfully { get; set; }
        public bool? IsMatureStudent { get; set; }
        public int? StudentVisaRequirementId { get; set; }
        public string HequalsOnEntryId { get; set; }
        public string EmaprogrammeOfStudyId { get; set; }
        public int? EmagroupId { get; set; }
        public string EmaflexibleBonusFrequencyId { get; set; }
        public bool? LocalAreaAssessmentReceived { get; set; }
        public string EmaadHocNote { get; set; }
        public bool Safeguarding { get; set; }
        public int? NumberOfYearsAtCurrentAddress { get; set; }
        public string Emanote { get; set; }
        public string Categories { get; set; }
        public bool? RestrictedUseAllowContactByPost { get; set; }
        public bool? RestrictedUseAllowContactByTelephone { get; set; }
        public bool? RestrictedUseAllowContactByEmail { get; set; }
        public bool? ParksMotorVehicleAtCollege { get; set; }
        public bool? ReceivedFreeSchoolMeals { get; set; }
        public int? TutorGroupId { get; set; }
        public int? CriminalConvictionId { get; set; }
        public int? StudentFirstLanguageId { get; set; }
        public int? LearnerStatusId { get; set; }
        public string MigrationId { get; set; }
        public bool? RestrictedUseAllowResearch { get; set; }
        public bool? RestrictedUseAllowLearningOpportunities { get; set; }
        public bool RestrictedUseNoContactIllness { get; set; }
        public string AdditionalLearningSupportLevelId { get; set; }
        public bool? HasLearningDifficultyAssessment { get; set; }
        public bool? HasDisabledStudentsAllowance { get; set; }
        public string LearnerSupportType5Id { get; set; }
        public bool? Alsrequested { get; set; }
        public DateTime? SchoolAttendedFrom { get; set; }
        public DateTime? SchoolAttendedTo { get; set; }
        public string BuildingSocietyRollNoEncrypted { get; set; }
        public string CarColour { get; set; }
        public string CarParkPassType { get; set; }
        public string UserDefined16 { get; set; }
        public string UserDefined17 { get; set; }
        public string UserDefined18 { get; set; }
        public string UserDefined19 { get; set; }
        public string UserDefined20 { get; set; }
        public string UserDefined21 { get; set; }
        public string UserDefined22 { get; set; }
        public string UserDefined23 { get; set; }
        public string UserDefined24 { get; set; }
        public string UserDefined25 { get; set; }
        public string UserDefined26 { get; set; }
        public string UserDefined27 { get; set; }
        public string UserDefined28 { get; set; }
        public string UserDefined29 { get; set; }
        public string UserDefined30 { get; set; }
        public bool? HasEducationHealthCarePlan { get; set; }
        public int? PlannedLearningHours { get; set; }
        public int? PlannedEephours { get; set; }
        public int? PreviousUklearningProvider { get; set; }
        public int? LocalDestinationOrganisationId { get; set; }
        public string LrsstudentContactTypeId { get; set; }
        public int? ReferralSourceId { get; set; }
        public DateTime? ReferralDate { get; set; }
        public string PriorAttainmentLevelInYearId { get; set; }
        public bool? LookedAfter { get; set; }
        public bool? CareLeaver { get; set; }
        public string GcsemathsAchievementId { get; set; }
        public string GcseenglishAchievementId { get; set; }
        public string PupilPremiumFundingEligibilityId { get; set; }
        public int? HefinTypeCash { get; set; }
        public int? HefinTypeNearCash { get; set; }
        public int? HefinTypeAccomDiscount { get; set; }
        public int? HefinTypeOther { get; set; }
        public int? FreeMealsEligibilityId { get; set; }
        public string PupilPremiumFundingEligibility2Id { get; set; }
        public bool? HighNeedsStudent { get; set; }
        public int? AdditionalBankId { get; set; }
        public int? AdditionalBankBranchId { get; set; }
        public string AdditionalBankAccountNoEncrypted { get; set; }
        public string AdditionalBankAccountNameEncrypted { get; set; }
        public bool ExcludeFromPlannedHoursCalculation { get; set; }
        public bool YoungParent { get; set; }
        public bool YoungCarer { get; set; }
        public bool? HasSpecialEducationNeeds { get; set; }
        public string GcseenglishQualificationGrade { get; set; }
        public string GcsemathsQualificationGrade { get; set; }
        public int? HouseholdSituation1Id { get; set; }
        public int? HouseholdSituation2Id { get; set; }
        public string LearningDiffOrDisId { get; set; }
        public int? GcsemathsConditionOfFundingId { get; set; }
        public int? GcseenglishConditionOfFundingId { get; set; }
        public bool? AchievedEnglishGcsebyEndOfYear11 { get; set; }
        public bool? AchievedMathsGcsebyEndOfYear11 { get; set; }
        public string UserDefined31 { get; set; }
        public string UserDefined32 { get; set; }
        public string UserDefined33 { get; set; }
        public string UserDefined34 { get; set; }
        public string UserDefined35 { get; set; }
        public string UserDefined36 { get; set; }
        public string UserDefined37 { get; set; }
        public string UserDefined38 { get; set; }
        public string UserDefined39 { get; set; }
        public string UserDefined40 { get; set; }
        public string UserDefined41 { get; set; }
        public string UserDefined42 { get; set; }
        public string UserDefined43 { get; set; }
        public string UserDefined44 { get; set; }
        public string UserDefined45 { get; set; }
        public bool? GiftedAndTalented { get; set; }
        public bool? Alsdeclined { get; set; }
        public string UcaspersonalId { get; set; }
        public int? PreMergerLearningProviderId { get; set; }
        public string UserDefinedDataProtection1 { get; set; }
        public string UserDefinedDataProtection2 { get; set; }
        public string UserDefinedDataProtection3 { get; set; }
        public string UserDefinedDataProtection4 { get; set; }
        public string UserDefinedDataProtection5 { get; set; }
        public string UserDefinedDataProtection6 { get; set; }
        public string UserDefinedDataProtection7 { get; set; }
        public string UserDefinedDataProtection8 { get; set; }
        public string UserDefinedDataProtection9 { get; set; }
        public string UserDefinedDataProtection10 { get; set; }
        public string UserDefinedDataProtection11 { get; set; }
        public string UserDefinedDataProtection12 { get; set; }
        public string UserDefinedDataProtection13 { get; set; }
        public string UserDefinedDataProtection14 { get; set; }
        public string UserDefinedDataProtection15 { get; set; }
        public string CampusIdentifier { get; set; }
        public int? Otjhours { get; set; }
        public bool HasConsentGiven { get; set; }
        public DateTime? ConsentGivenDate { get; set; }
        public bool AcceptMarketingConsent { get; set; }
        public bool AcceptShareInfoConsent { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public string ContactedBy { get; set; }
        public string Gdprnotes { get; set; }
        public bool CanBeContactBySms { get; set; }
        public bool CanBeContactBySocialMedia { get; set; }
        public bool CanBeSharedByEmail { get; set; }
        public bool CanBeSharedByWebSite { get; set; }
        public bool CanBeSharedBySocialMedia { get; set; }
        public bool? GdprallowContactByPhone { get; set; }
        public bool? GdprallowContactByPost { get; set; }
        public bool? GdprallowContactByEmail { get; set; }
    }
}
